language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
script: make test
notifications:
  email: false
env:
  global:
    - DATABASE_URL='postgres://postgres@localhost/pagination'
  matrix:
    - DJANGO='django~=1.8.0'
install:
  - psql -c 'CREATE DATABASE pagination' -U postgres;
  - pip install -r requirements.txt --use-wheel
  - pip install $DJANGO --use-wheel
